//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbContabUsersModel", "FK_CompaniasYUsuarios_aspnet_Users", "aspnet_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.Users.aspnet_Users), "CompaniasYUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.Users.CompaniasYUsuario), true)]
[assembly: EdmRelationshipAttribute("dbContabUsersModel", "FK_CompaniasYUsuarios_Companias", "Companias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.Users.Compania), "CompaniasYUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.Users.CompaniasYUsuario), true)]
[assembly: EdmRelationshipAttribute("dbContabUsersModel", "FK_tCiaSeleccionada_Companias", "Compania", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.Users.Compania), "tCiaSeleccionada", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.Users.tCiaSeleccionada), true)]

#endregion

namespace ContabSysNet_Web.ModelosDatos_EF.Users
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbContabUsersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbContabUsersEntities object using the connection string found in the 'dbContabUsersEntities' section of the application configuration file.
        /// </summary>
        public dbContabUsersEntities() : base("name=dbContabUsersEntities", "dbContabUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbContabUsersEntities object.
        /// </summary>
        public dbContabUsersEntities(string connectionString) : base(connectionString, "dbContabUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbContabUsersEntities object.
        /// </summary>
        public dbContabUsersEntities(EntityConnection connection) : base(connection, "dbContabUsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aspnet_Users> aspnet_Users
        {
            get
            {
                if ((_aspnet_Users == null))
                {
                    _aspnet_Users = base.CreateObjectSet<aspnet_Users>("aspnet_Users");
                }
                return _aspnet_Users;
            }
        }
        private ObjectSet<aspnet_Users> _aspnet_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Compania> Companias
        {
            get
            {
                if ((_Companias == null))
                {
                    _Companias = base.CreateObjectSet<Compania>("Companias");
                }
                return _Companias;
            }
        }
        private ObjectSet<Compania> _Companias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompaniasYUsuario> CompaniasYUsuarios
        {
            get
            {
                if ((_CompaniasYUsuarios == null))
                {
                    _CompaniasYUsuarios = base.CreateObjectSet<CompaniasYUsuario>("CompaniasYUsuarios");
                }
                return _CompaniasYUsuarios;
            }
        }
        private ObjectSet<CompaniasYUsuario> _CompaniasYUsuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tCiaSeleccionada> tCiaSeleccionadas
        {
            get
            {
                if ((_tCiaSeleccionadas == null))
                {
                    _tCiaSeleccionadas = base.CreateObjectSet<tCiaSeleccionada>("tCiaSeleccionadas");
                }
                return _tCiaSeleccionadas;
            }
        }
        private ObjectSet<tCiaSeleccionada> _tCiaSeleccionadas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aspnet_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaspnet_Users(aspnet_Users aspnet_Users)
        {
            base.AddObject("aspnet_Users", aspnet_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanias(Compania compania)
        {
            base.AddObject("Companias", compania);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompaniasYUsuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompaniasYUsuarios(CompaniasYUsuario companiasYUsuario)
        {
            base.AddObject("CompaniasYUsuarios", companiasYUsuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tCiaSeleccionadas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotCiaSeleccionadas(tCiaSeleccionada tCiaSeleccionada)
        {
            base.AddObject("tCiaSeleccionadas", tCiaSeleccionada);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbContabUsersModel", Name="aspnet_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aspnet_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aspnet_Users object.
        /// </summary>
        /// <param name="applicationId">Initial value of the ApplicationId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="loweredUserName">Initial value of the LoweredUserName property.</param>
        /// <param name="isAnonymous">Initial value of the IsAnonymous property.</param>
        /// <param name="lastActivityDate">Initial value of the LastActivityDate property.</param>
        public static aspnet_Users Createaspnet_Users(global::System.Guid applicationId, global::System.Guid userId, global::System.String userName, global::System.String loweredUserName, global::System.Boolean isAnonymous, global::System.DateTime lastActivityDate)
        {
            aspnet_Users aspnet_Users = new aspnet_Users();
            aspnet_Users.ApplicationId = applicationId;
            aspnet_Users.UserId = userId;
            aspnet_Users.UserName = userName;
            aspnet_Users.LoweredUserName = loweredUserName;
            aspnet_Users.IsAnonymous = isAnonymous;
            aspnet_Users.LastActivityDate = lastActivityDate;
            return aspnet_Users;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                OnApplicationIdChanging(value);
                ReportPropertyChanging("ApplicationId");
                _ApplicationId = StructuralObject.SetValidValue(value, "ApplicationId");
                ReportPropertyChanged("ApplicationId");
                OnApplicationIdChanged();
            }
        }
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoweredUserName
        {
            get
            {
                return _LoweredUserName;
            }
            set
            {
                OnLoweredUserNameChanging(value);
                ReportPropertyChanging("LoweredUserName");
                _LoweredUserName = StructuralObject.SetValidValue(value, false, "LoweredUserName");
                ReportPropertyChanged("LoweredUserName");
                OnLoweredUserNameChanged();
            }
        }
        private global::System.String _LoweredUserName;
        partial void OnLoweredUserNameChanging(global::System.String value);
        partial void OnLoweredUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileAlias
        {
            get
            {
                return _MobileAlias;
            }
            set
            {
                OnMobileAliasChanging(value);
                ReportPropertyChanging("MobileAlias");
                _MobileAlias = StructuralObject.SetValidValue(value, true, "MobileAlias");
                ReportPropertyChanged("MobileAlias");
                OnMobileAliasChanged();
            }
        }
        private global::System.String _MobileAlias;
        partial void OnMobileAliasChanging(global::System.String value);
        partial void OnMobileAliasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAnonymous
        {
            get
            {
                return _IsAnonymous;
            }
            set
            {
                OnIsAnonymousChanging(value);
                ReportPropertyChanging("IsAnonymous");
                _IsAnonymous = StructuralObject.SetValidValue(value, "IsAnonymous");
                ReportPropertyChanged("IsAnonymous");
                OnIsAnonymousChanged();
            }
        }
        private global::System.Boolean _IsAnonymous;
        partial void OnIsAnonymousChanging(global::System.Boolean value);
        partial void OnIsAnonymousChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value, "LastActivityDate");
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbContabUsersModel", "FK_CompaniasYUsuarios_aspnet_Users", "CompaniasYUsuarios")]
        public EntityCollection<CompaniasYUsuario> CompaniasYUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CompaniasYUsuario>("dbContabUsersModel.FK_CompaniasYUsuarios_aspnet_Users", "CompaniasYUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CompaniasYUsuario>("dbContabUsersModel.FK_CompaniasYUsuarios_aspnet_Users", "CompaniasYUsuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbContabUsersModel", Name="Compania")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compania : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Compania object.
        /// </summary>
        /// <param name="numero">Initial value of the Numero property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="nombreCorto">Initial value of the NombreCorto property.</param>
        /// <param name="abreviatura">Initial value of the Abreviatura property.</param>
        public static Compania CreateCompania(global::System.Int32 numero, global::System.String nombre, global::System.String nombreCorto, global::System.String abreviatura)
        {
            Compania compania = new Compania();
            compania.Numero = numero;
            compania.Nombre = nombre;
            compania.NombreCorto = nombreCorto;
            compania.Abreviatura = abreviatura;
            return compania;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                if (_Numero != value)
                {
                    OnNumeroChanging(value);
                    ReportPropertyChanging("Numero");
                    _Numero = StructuralObject.SetValidValue(value, "Numero");
                    ReportPropertyChanged("Numero");
                    OnNumeroChanged();
                }
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCorto
        {
            get
            {
                return _NombreCorto;
            }
            set
            {
                OnNombreCortoChanging(value);
                ReportPropertyChanging("NombreCorto");
                _NombreCorto = StructuralObject.SetValidValue(value, false, "NombreCorto");
                ReportPropertyChanged("NombreCorto");
                OnNombreCortoChanged();
            }
        }
        private global::System.String _NombreCorto;
        partial void OnNombreCortoChanging(global::System.String value);
        partial void OnNombreCortoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Abreviatura
        {
            get
            {
                return _Abreviatura;
            }
            set
            {
                OnAbreviaturaChanging(value);
                ReportPropertyChanging("Abreviatura");
                _Abreviatura = StructuralObject.SetValidValue(value, false, "Abreviatura");
                ReportPropertyChanged("Abreviatura");
                OnAbreviaturaChanged();
            }
        }
        private global::System.String _Abreviatura;
        partial void OnAbreviaturaChanging(global::System.String value);
        partial void OnAbreviaturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rif
        {
            get
            {
                return _Rif;
            }
            set
            {
                OnRifChanging(value);
                ReportPropertyChanging("Rif");
                _Rif = StructuralObject.SetValidValue(value, true, "Rif");
                ReportPropertyChanged("Rif");
                OnRifChanged();
            }
        }
        private global::System.String _Rif;
        partial void OnRifChanging(global::System.String value);
        partial void OnRifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true, "Direccion");
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true, "Ciudad");
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EntidadFederal
        {
            get
            {
                return _EntidadFederal;
            }
            set
            {
                OnEntidadFederalChanging(value);
                ReportPropertyChanging("EntidadFederal");
                _EntidadFederal = StructuralObject.SetValidValue(value, true, "EntidadFederal");
                ReportPropertyChanged("EntidadFederal");
                OnEntidadFederalChanged();
            }
        }
        private global::System.String _EntidadFederal;
        partial void OnEntidadFederalChanging(global::System.String value);
        partial void OnEntidadFederalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZonaPostal
        {
            get
            {
                return _ZonaPostal;
            }
            set
            {
                OnZonaPostalChanging(value);
                ReportPropertyChanging("ZonaPostal");
                _ZonaPostal = StructuralObject.SetValidValue(value, true, "ZonaPostal");
                ReportPropertyChanged("ZonaPostal");
                OnZonaPostalChanged();
            }
        }
        private global::System.String _ZonaPostal;
        partial void OnZonaPostalChanging(global::System.String value);
        partial void OnZonaPostalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono1
        {
            get
            {
                return _Telefono1;
            }
            set
            {
                OnTelefono1Changing(value);
                ReportPropertyChanging("Telefono1");
                _Telefono1 = StructuralObject.SetValidValue(value, true, "Telefono1");
                ReportPropertyChanged("Telefono1");
                OnTelefono1Changed();
            }
        }
        private global::System.String _Telefono1;
        partial void OnTelefono1Changing(global::System.String value);
        partial void OnTelefono1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono2
        {
            get
            {
                return _Telefono2;
            }
            set
            {
                OnTelefono2Changing(value);
                ReportPropertyChanging("Telefono2");
                _Telefono2 = StructuralObject.SetValidValue(value, true, "Telefono2");
                ReportPropertyChanged("Telefono2");
                OnTelefono2Changed();
            }
        }
        private global::System.String _Telefono2;
        partial void OnTelefono2Changing(global::System.String value);
        partial void OnTelefono2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true, "Fax");
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailServerName
        {
            get
            {
                return _EmailServerName;
            }
            set
            {
                OnEmailServerNameChanging(value);
                ReportPropertyChanging("EmailServerName");
                _EmailServerName = StructuralObject.SetValidValue(value, true, "EmailServerName");
                ReportPropertyChanged("EmailServerName");
                OnEmailServerNameChanged();
            }
        }
        private global::System.String _EmailServerName;
        partial void OnEmailServerNameChanging(global::System.String value);
        partial void OnEmailServerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmailServerPort
        {
            get
            {
                return _EmailServerPort;
            }
            set
            {
                OnEmailServerPortChanging(value);
                ReportPropertyChanging("EmailServerPort");
                _EmailServerPort = StructuralObject.SetValidValue(value, "EmailServerPort");
                ReportPropertyChanged("EmailServerPort");
                OnEmailServerPortChanged();
            }
        }
        private Nullable<global::System.Int32> _EmailServerPort;
        partial void OnEmailServerPortChanging(Nullable<global::System.Int32> value);
        partial void OnEmailServerPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EmailServerSSLFlag
        {
            get
            {
                return _EmailServerSSLFlag;
            }
            set
            {
                OnEmailServerSSLFlagChanging(value);
                ReportPropertyChanging("EmailServerSSLFlag");
                _EmailServerSSLFlag = StructuralObject.SetValidValue(value, "EmailServerSSLFlag");
                ReportPropertyChanged("EmailServerSSLFlag");
                OnEmailServerSSLFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _EmailServerSSLFlag;
        partial void OnEmailServerSSLFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnEmailServerSSLFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailServerCredentialsUserName
        {
            get
            {
                return _EmailServerCredentialsUserName;
            }
            set
            {
                OnEmailServerCredentialsUserNameChanging(value);
                ReportPropertyChanging("EmailServerCredentialsUserName");
                _EmailServerCredentialsUserName = StructuralObject.SetValidValue(value, true, "EmailServerCredentialsUserName");
                ReportPropertyChanged("EmailServerCredentialsUserName");
                OnEmailServerCredentialsUserNameChanged();
            }
        }
        private global::System.String _EmailServerCredentialsUserName;
        partial void OnEmailServerCredentialsUserNameChanging(global::System.String value);
        partial void OnEmailServerCredentialsUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailServerCredentialsPassword
        {
            get
            {
                return _EmailServerCredentialsPassword;
            }
            set
            {
                OnEmailServerCredentialsPasswordChanging(value);
                ReportPropertyChanging("EmailServerCredentialsPassword");
                _EmailServerCredentialsPassword = StructuralObject.SetValidValue(value, true, "EmailServerCredentialsPassword");
                ReportPropertyChanged("EmailServerCredentialsPassword");
                OnEmailServerCredentialsPasswordChanged();
            }
        }
        private global::System.String _EmailServerCredentialsPassword;
        partial void OnEmailServerCredentialsPasswordChanging(global::System.String value);
        partial void OnEmailServerCredentialsPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MonedaDefecto
        {
            get
            {
                return _MonedaDefecto;
            }
            set
            {
                OnMonedaDefectoChanging(value);
                ReportPropertyChanging("MonedaDefecto");
                _MonedaDefecto = StructuralObject.SetValidValue(value, "MonedaDefecto");
                ReportPropertyChanged("MonedaDefecto");
                OnMonedaDefectoChanged();
            }
        }
        private Nullable<global::System.Int32> _MonedaDefecto;
        partial void OnMonedaDefectoChanging(Nullable<global::System.Int32> value);
        partial void OnMonedaDefectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SuspendidoFlag
        {
            get
            {
                return _SuspendidoFlag;
            }
            set
            {
                OnSuspendidoFlagChanging(value);
                ReportPropertyChanging("SuspendidoFlag");
                _SuspendidoFlag = StructuralObject.SetValidValue(value, "SuspendidoFlag");
                ReportPropertyChanged("SuspendidoFlag");
                OnSuspendidoFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _SuspendidoFlag;
        partial void OnSuspendidoFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnSuspendidoFlagChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbContabUsersModel", "FK_CompaniasYUsuarios_Companias", "CompaniasYUsuarios")]
        public EntityCollection<CompaniasYUsuario> CompaniasYUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CompaniasYUsuario>("dbContabUsersModel.FK_CompaniasYUsuarios_Companias", "CompaniasYUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CompaniasYUsuario>("dbContabUsersModel.FK_CompaniasYUsuarios_Companias", "CompaniasYUsuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbContabUsersModel", "FK_tCiaSeleccionada_Companias", "tCiaSeleccionada")]
        public EntityCollection<tCiaSeleccionada> tCiaSeleccionadas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tCiaSeleccionada>("dbContabUsersModel.FK_tCiaSeleccionada_Companias", "tCiaSeleccionada");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tCiaSeleccionada>("dbContabUsersModel.FK_tCiaSeleccionada_Companias", "tCiaSeleccionada", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbContabUsersModel", Name="CompaniasYUsuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompaniasYUsuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompaniasYUsuario object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="compania">Initial value of the Compania property.</param>
        /// <param name="usuario">Initial value of the Usuario property.</param>
        public static CompaniasYUsuario CreateCompaniasYUsuario(global::System.Int32 pK, global::System.Int32 compania, global::System.Guid usuario)
        {
            CompaniasYUsuario companiasYUsuario = new CompaniasYUsuario();
            companiasYUsuario.PK = pK;
            companiasYUsuario.Compania = compania;
            companiasYUsuario.Usuario = usuario;
            return companiasYUsuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, "PK");
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int32 _PK;
        partial void OnPKChanging(global::System.Int32 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Compania
        {
            get
            {
                return _Compania;
            }
            set
            {
                OnCompaniaChanging(value);
                ReportPropertyChanging("Compania");
                _Compania = StructuralObject.SetValidValue(value, "Compania");
                ReportPropertyChanged("Compania");
                OnCompaniaChanged();
            }
        }
        private global::System.Int32 _Compania;
        partial void OnCompaniaChanging(global::System.Int32 value);
        partial void OnCompaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, "Usuario");
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.Guid _Usuario;
        partial void OnUsuarioChanging(global::System.Guid value);
        partial void OnUsuarioChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbContabUsersModel", "FK_CompaniasYUsuarios_aspnet_Users", "aspnet_Users")]
        public aspnet_Users aspnet_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aspnet_Users>("dbContabUsersModel.FK_CompaniasYUsuarios_aspnet_Users", "aspnet_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aspnet_Users>("dbContabUsersModel.FK_CompaniasYUsuarios_aspnet_Users", "aspnet_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aspnet_Users> aspnet_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aspnet_Users>("dbContabUsersModel.FK_CompaniasYUsuarios_aspnet_Users", "aspnet_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aspnet_Users>("dbContabUsersModel.FK_CompaniasYUsuarios_aspnet_Users", "aspnet_Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbContabUsersModel", "FK_CompaniasYUsuarios_Companias", "Companias")]
        public Compania Compania1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compania>("dbContabUsersModel.FK_CompaniasYUsuarios_Companias", "Companias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compania>("dbContabUsersModel.FK_CompaniasYUsuarios_Companias", "Companias").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compania> Compania1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compania>("dbContabUsersModel.FK_CompaniasYUsuarios_Companias", "Companias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compania>("dbContabUsersModel.FK_CompaniasYUsuarios_Companias", "Companias", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbContabUsersModel", Name="tCiaSeleccionada")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tCiaSeleccionada : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tCiaSeleccionada object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="ciaSeleccionada">Initial value of the CiaSeleccionada property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="nombreCorto">Initial value of the NombreCorto property.</param>
        /// <param name="usuario">Initial value of the Usuario property.</param>
        public static tCiaSeleccionada CreatetCiaSeleccionada(global::System.Int32 id, global::System.Int32 ciaSeleccionada, global::System.String nombre, global::System.String nombreCorto, global::System.Int32 usuario)
        {
            tCiaSeleccionada tCiaSeleccionada = new tCiaSeleccionada();
            tCiaSeleccionada.ID = id;
            tCiaSeleccionada.CiaSeleccionada = ciaSeleccionada;
            tCiaSeleccionada.Nombre = nombre;
            tCiaSeleccionada.NombreCorto = nombreCorto;
            tCiaSeleccionada.Usuario = usuario;
            return tCiaSeleccionada;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CiaSeleccionada
        {
            get
            {
                return _CiaSeleccionada;
            }
            set
            {
                OnCiaSeleccionadaChanging(value);
                ReportPropertyChanging("CiaSeleccionada");
                _CiaSeleccionada = StructuralObject.SetValidValue(value, "CiaSeleccionada");
                ReportPropertyChanged("CiaSeleccionada");
                OnCiaSeleccionadaChanged();
            }
        }
        private global::System.Int32 _CiaSeleccionada;
        partial void OnCiaSeleccionadaChanging(global::System.Int32 value);
        partial void OnCiaSeleccionadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCorto
        {
            get
            {
                return _NombreCorto;
            }
            set
            {
                OnNombreCortoChanging(value);
                ReportPropertyChanging("NombreCorto");
                _NombreCorto = StructuralObject.SetValidValue(value, false, "NombreCorto");
                ReportPropertyChanged("NombreCorto");
                OnNombreCortoChanged();
            }
        }
        private global::System.String _NombreCorto;
        partial void OnNombreCortoChanging(global::System.String value);
        partial void OnNombreCortoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, "Usuario");
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.Int32 _Usuario;
        partial void OnUsuarioChanging(global::System.Int32 value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UsuarioLS
        {
            get
            {
                return _UsuarioLS;
            }
            set
            {
                OnUsuarioLSChanging(value);
                ReportPropertyChanging("UsuarioLS");
                _UsuarioLS = StructuralObject.SetValidValue(value, true, "UsuarioLS");
                ReportPropertyChanged("UsuarioLS");
                OnUsuarioLSChanged();
            }
        }
        private global::System.String _UsuarioLS;
        partial void OnUsuarioLSChanging(global::System.String value);
        partial void OnUsuarioLSChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbContabUsersModel", "FK_tCiaSeleccionada_Companias", "Compania")]
        public Compania Compania
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compania>("dbContabUsersModel.FK_tCiaSeleccionada_Companias", "Compania").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compania>("dbContabUsersModel.FK_tCiaSeleccionada_Companias", "Compania").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compania> CompaniaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compania>("dbContabUsersModel.FK_tCiaSeleccionada_Companias", "Compania");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compania>("dbContabUsersModel.FK_tCiaSeleccionada_Companias", "Compania", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
