//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_CajasChicas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_CajasChicas), "CajaChica_Reposiciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Reposiciones), true)]
[assembly: EdmRelationshipAttribute("ControlCajaChicaModel", "FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_CajasChicas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_CajasChicas), "CajaChica_Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Usuarios), true)]
[assembly: EdmRelationshipAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Reposiciones), "CajaChica_Reposiciones_Estados", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Reposiciones_Estados), true)]
[assembly: EdmRelationshipAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Reposiciones), "CajaChica_Reposiciones_Gastos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Reposiciones_Gastos), true)]
[assembly: EdmRelationshipAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Rubros", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Rubros), "CajaChica_Reposiciones_Gastos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Reposiciones_Gastos), true)]
[assembly: EdmRelationshipAttribute("ControlCajaChicaModel", "FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_Rubros", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_Rubros), "CajaChica_RubrosCuentasContables", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContabSysNet_Web.ModelosDatos_EF.CajaChica.CajaChica_RubrosCuentasContables), true)]

#endregion

namespace ContabSysNet_Web.ModelosDatos_EF.CajaChica
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ControlCajaChicaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ControlCajaChicaEntities object using the connection string found in the 'ControlCajaChicaEntities' section of the application configuration file.
        /// </summary>
        public ControlCajaChicaEntities() : base("name=ControlCajaChicaEntities", "ControlCajaChicaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ControlCajaChicaEntities object.
        /// </summary>
        public ControlCajaChicaEntities(string connectionString) : base(connectionString, "ControlCajaChicaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ControlCajaChicaEntities object.
        /// </summary>
        public ControlCajaChicaEntities(EntityConnection connection) : base(connection, "ControlCajaChicaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_CajasChicas> CajaChica_CajasChicas
        {
            get
            {
                if ((_CajaChica_CajasChicas == null))
                {
                    _CajaChica_CajasChicas = base.CreateObjectSet<CajaChica_CajasChicas>("CajaChica_CajasChicas");
                }
                return _CajaChica_CajasChicas;
            }
        }
        private ObjectSet<CajaChica_CajasChicas> _CajaChica_CajasChicas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_Reposiciones> CajaChica_Reposiciones
        {
            get
            {
                if ((_CajaChica_Reposiciones == null))
                {
                    _CajaChica_Reposiciones = base.CreateObjectSet<CajaChica_Reposiciones>("CajaChica_Reposiciones");
                }
                return _CajaChica_Reposiciones;
            }
        }
        private ObjectSet<CajaChica_Reposiciones> _CajaChica_Reposiciones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_Reposiciones_Estados> CajaChica_Reposiciones_Estados
        {
            get
            {
                if ((_CajaChica_Reposiciones_Estados == null))
                {
                    _CajaChica_Reposiciones_Estados = base.CreateObjectSet<CajaChica_Reposiciones_Estados>("CajaChica_Reposiciones_Estados");
                }
                return _CajaChica_Reposiciones_Estados;
            }
        }
        private ObjectSet<CajaChica_Reposiciones_Estados> _CajaChica_Reposiciones_Estados;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_Reposiciones_Gastos> CajaChica_Reposiciones_Gastos
        {
            get
            {
                if ((_CajaChica_Reposiciones_Gastos == null))
                {
                    _CajaChica_Reposiciones_Gastos = base.CreateObjectSet<CajaChica_Reposiciones_Gastos>("CajaChica_Reposiciones_Gastos");
                }
                return _CajaChica_Reposiciones_Gastos;
            }
        }
        private ObjectSet<CajaChica_Reposiciones_Gastos> _CajaChica_Reposiciones_Gastos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_Rubros> CajaChica_Rubros
        {
            get
            {
                if ((_CajaChica_Rubros == null))
                {
                    _CajaChica_Rubros = base.CreateObjectSet<CajaChica_Rubros>("CajaChica_Rubros");
                }
                return _CajaChica_Rubros;
            }
        }
        private ObjectSet<CajaChica_Rubros> _CajaChica_Rubros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_RubrosCuentasContables> CajaChica_RubrosCuentasContables
        {
            get
            {
                if ((_CajaChica_RubrosCuentasContables == null))
                {
                    _CajaChica_RubrosCuentasContables = base.CreateObjectSet<CajaChica_RubrosCuentasContables>("CajaChica_RubrosCuentasContables");
                }
                return _CajaChica_RubrosCuentasContables;
            }
        }
        private ObjectSet<CajaChica_RubrosCuentasContables> _CajaChica_RubrosCuentasContables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_Usuarios> CajaChica_Usuarios
        {
            get
            {
                if ((_CajaChica_Usuarios == null))
                {
                    _CajaChica_Usuarios = base.CreateObjectSet<CajaChica_Usuarios>("CajaChica_Usuarios");
                }
                return _CajaChica_Usuarios;
            }
        }
        private ObjectSet<CajaChica_Usuarios> _CajaChica_Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CajaChica_Parametros> CajaChica_Parametros
        {
            get
            {
                if ((_CajaChica_Parametros == null))
                {
                    _CajaChica_Parametros = base.CreateObjectSet<CajaChica_Parametros>("CajaChica_Parametros");
                }
                return _CajaChica_Parametros;
            }
        }
        private ObjectSet<CajaChica_Parametros> _CajaChica_Parametros;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_CajasChicas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_CajasChicas(CajaChica_CajasChicas cajaChica_CajasChicas)
        {
            base.AddObject("CajaChica_CajasChicas", cajaChica_CajasChicas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_Reposiciones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_Reposiciones(CajaChica_Reposiciones cajaChica_Reposiciones)
        {
            base.AddObject("CajaChica_Reposiciones", cajaChica_Reposiciones);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_Reposiciones_Estados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_Reposiciones_Estados(CajaChica_Reposiciones_Estados cajaChica_Reposiciones_Estados)
        {
            base.AddObject("CajaChica_Reposiciones_Estados", cajaChica_Reposiciones_Estados);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_Reposiciones_Gastos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_Reposiciones_Gastos(CajaChica_Reposiciones_Gastos cajaChica_Reposiciones_Gastos)
        {
            base.AddObject("CajaChica_Reposiciones_Gastos", cajaChica_Reposiciones_Gastos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_Rubros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_Rubros(CajaChica_Rubros cajaChica_Rubros)
        {
            base.AddObject("CajaChica_Rubros", cajaChica_Rubros);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_RubrosCuentasContables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_RubrosCuentasContables(CajaChica_RubrosCuentasContables cajaChica_RubrosCuentasContables)
        {
            base.AddObject("CajaChica_RubrosCuentasContables", cajaChica_RubrosCuentasContables);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_Usuarios(CajaChica_Usuarios cajaChica_Usuarios)
        {
            base.AddObject("CajaChica_Usuarios", cajaChica_Usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CajaChica_Parametros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCajaChica_Parametros(CajaChica_Parametros cajaChica_Parametros)
        {
            base.AddObject("CajaChica_Parametros", cajaChica_Parametros);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_CajasChicas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_CajasChicas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_CajasChicas object.
        /// </summary>
        /// <param name="cajaChica">Initial value of the CajaChica property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="ciaContab">Initial value of the CiaContab property.</param>
        public static CajaChica_CajasChicas CreateCajaChica_CajasChicas(global::System.Int16 cajaChica, global::System.String descripcion, global::System.Int32 ciaContab)
        {
            CajaChica_CajasChicas cajaChica_CajasChicas = new CajaChica_CajasChicas();
            cajaChica_CajasChicas.CajaChica = cajaChica;
            cajaChica_CajasChicas.Descripcion = descripcion;
            cajaChica_CajasChicas.CiaContab = ciaContab;
            return cajaChica_CajasChicas;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CajaChica
        {
            get
            {
                return _CajaChica;
            }
            set
            {
                if (_CajaChica != value)
                {
                    OnCajaChicaChanging(value);
                    ReportPropertyChanging("CajaChica");
                    _CajaChica = StructuralObject.SetValidValue(value, "CajaChica");
                    ReportPropertyChanged("CajaChica");
                    OnCajaChicaChanged();
                }
            }
        }
        private global::System.Int16 _CajaChica;
        partial void OnCajaChicaChanging(global::System.Int16 value);
        partial void OnCajaChicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CiaContab
        {
            get
            {
                return _CiaContab;
            }
            set
            {
                OnCiaContabChanging(value);
                ReportPropertyChanging("CiaContab");
                _CiaContab = StructuralObject.SetValidValue(value, "CiaContab");
                ReportPropertyChanged("CiaContab");
                OnCiaContabChanged();
            }
        }
        private global::System.Int32 _CiaContab;
        partial void OnCiaContabChanging(global::System.Int32 value);
        partial void OnCiaContabChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_Reposiciones")]
        public EntityCollection<CajaChica_Reposiciones> CajaChica_Reposiciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_Reposiciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_Reposiciones", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_Usuarios")]
        public EntityCollection<CajaChica_Usuarios> CajaChica_Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CajaChica_Usuarios>("ControlCajaChicaModel.FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CajaChica_Usuarios>("ControlCajaChicaModel.FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_Parametros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_Parametros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_Parametros object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tipoAsiento">Initial value of the TipoAsiento property.</param>
        /// <param name="cuentaContablePuenteID">Initial value of the CuentaContablePuenteID property.</param>
        /// <param name="cia">Initial value of the Cia property.</param>
        public static CajaChica_Parametros CreateCajaChica_Parametros(global::System.Int32 id, global::System.String tipoAsiento, global::System.Int32 cuentaContablePuenteID, global::System.Int32 cia)
        {
            CajaChica_Parametros cajaChica_Parametros = new CajaChica_Parametros();
            cajaChica_Parametros.ID = id;
            cajaChica_Parametros.TipoAsiento = tipoAsiento;
            cajaChica_Parametros.CuentaContablePuenteID = cuentaContablePuenteID;
            cajaChica_Parametros.Cia = cia;
            return cajaChica_Parametros;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoAsiento
        {
            get
            {
                return _TipoAsiento;
            }
            set
            {
                OnTipoAsientoChanging(value);
                ReportPropertyChanging("TipoAsiento");
                _TipoAsiento = StructuralObject.SetValidValue(value, false, "TipoAsiento");
                ReportPropertyChanged("TipoAsiento");
                OnTipoAsientoChanged();
            }
        }
        private global::System.String _TipoAsiento;
        partial void OnTipoAsientoChanging(global::System.String value);
        partial void OnTipoAsientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CuentaContablePuenteID
        {
            get
            {
                return _CuentaContablePuenteID;
            }
            set
            {
                OnCuentaContablePuenteIDChanging(value);
                ReportPropertyChanging("CuentaContablePuenteID");
                _CuentaContablePuenteID = StructuralObject.SetValidValue(value, "CuentaContablePuenteID");
                ReportPropertyChanged("CuentaContablePuenteID");
                OnCuentaContablePuenteIDChanged();
            }
        }
        private global::System.Int32 _CuentaContablePuenteID;
        partial void OnCuentaContablePuenteIDChanging(global::System.Int32 value);
        partial void OnCuentaContablePuenteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cia
        {
            get
            {
                return _Cia;
            }
            set
            {
                OnCiaChanging(value);
                ReportPropertyChanging("Cia");
                _Cia = StructuralObject.SetValidValue(value, "Cia");
                ReportPropertyChanged("Cia");
                OnCiaChanged();
            }
        }
        private global::System.Int32 _Cia;
        partial void OnCiaChanging(global::System.Int32 value);
        partial void OnCiaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_Reposiciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_Reposiciones : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_Reposiciones object.
        /// </summary>
        /// <param name="reposicion">Initial value of the Reposicion property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="cajaChica">Initial value of the CajaChica property.</param>
        /// <param name="estadoActual">Initial value of the EstadoActual property.</param>
        public static CajaChica_Reposiciones CreateCajaChica_Reposiciones(global::System.Int32 reposicion, global::System.DateTime fecha, global::System.Int16 cajaChica, global::System.String estadoActual)
        {
            CajaChica_Reposiciones cajaChica_Reposiciones = new CajaChica_Reposiciones();
            cajaChica_Reposiciones.Reposicion = reposicion;
            cajaChica_Reposiciones.Fecha = fecha;
            cajaChica_Reposiciones.CajaChica = cajaChica;
            cajaChica_Reposiciones.EstadoActual = estadoActual;
            return cajaChica_Reposiciones;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Reposicion
        {
            get
            {
                return _Reposicion;
            }
            set
            {
                if (_Reposicion != value)
                {
                    OnReposicionChanging(value);
                    ReportPropertyChanging("Reposicion");
                    _Reposicion = StructuralObject.SetValidValue(value, "Reposicion");
                    ReportPropertyChanged("Reposicion");
                    OnReposicionChanged();
                }
            }
        }
        private global::System.Int32 _Reposicion;
        partial void OnReposicionChanging(global::System.Int32 value);
        partial void OnReposicionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CajaChica
        {
            get
            {
                return _CajaChica;
            }
            set
            {
                OnCajaChicaChanging(value);
                ReportPropertyChanging("CajaChica");
                _CajaChica = StructuralObject.SetValidValue(value, "CajaChica");
                ReportPropertyChanged("CajaChica");
                OnCajaChicaChanged();
            }
        }
        private global::System.Int16 _CajaChica;
        partial void OnCajaChicaChanging(global::System.Int16 value);
        partial void OnCajaChicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            set
            {
                OnObservacionesChanging(value);
                ReportPropertyChanging("Observaciones");
                _Observaciones = StructuralObject.SetValidValue(value, true, "Observaciones");
                ReportPropertyChanged("Observaciones");
                OnObservacionesChanged();
            }
        }
        private global::System.String _Observaciones;
        partial void OnObservacionesChanging(global::System.String value);
        partial void OnObservacionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EstadoActual
        {
            get
            {
                return _EstadoActual;
            }
            set
            {
                OnEstadoActualChanging(value);
                ReportPropertyChanging("EstadoActual");
                _EstadoActual = StructuralObject.SetValidValue(value, false, "EstadoActual");
                ReportPropertyChanged("EstadoActual");
                OnEstadoActualChanged();
            }
        }
        private global::System.String _EstadoActual;
        partial void OnEstadoActualChanging(global::System.String value);
        partial void OnEstadoActualChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_CajasChicas")]
        public CajaChica_CajasChicas CajaChica_CajasChicas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_CajasChicas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_CajasChicas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CajaChica_CajasChicas> CajaChica_CajasChicasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_CajasChicas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_CajaChica_CajasChicas", "CajaChica_CajasChicas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones_Estados")]
        public EntityCollection<CajaChica_Reposiciones_Estados> CajaChica_Reposiciones_Estados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CajaChica_Reposiciones_Estados>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones_Estados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CajaChica_Reposiciones_Estados>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones_Estados", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones_Gastos")]
        public EntityCollection<CajaChica_Reposiciones_Gastos> CajaChica_Reposiciones_Gastos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CajaChica_Reposiciones_Gastos>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones_Gastos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CajaChica_Reposiciones_Gastos>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones_Gastos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_Reposiciones_Estados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_Reposiciones_Estados : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_Reposiciones_Estados object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="reposicion">Initial value of the Reposicion property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="nombreUsuario">Initial value of the NombreUsuario property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static CajaChica_Reposiciones_Estados CreateCajaChica_Reposiciones_Estados(global::System.Int32 id, global::System.Int32 reposicion, global::System.DateTime fecha, global::System.String nombreUsuario, global::System.String estado)
        {
            CajaChica_Reposiciones_Estados cajaChica_Reposiciones_Estados = new CajaChica_Reposiciones_Estados();
            cajaChica_Reposiciones_Estados.ID = id;
            cajaChica_Reposiciones_Estados.Reposicion = reposicion;
            cajaChica_Reposiciones_Estados.Fecha = fecha;
            cajaChica_Reposiciones_Estados.NombreUsuario = nombreUsuario;
            cajaChica_Reposiciones_Estados.Estado = estado;
            return cajaChica_Reposiciones_Estados;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Reposicion
        {
            get
            {
                return _Reposicion;
            }
            set
            {
                OnReposicionChanging(value);
                ReportPropertyChanging("Reposicion");
                _Reposicion = StructuralObject.SetValidValue(value, "Reposicion");
                ReportPropertyChanged("Reposicion");
                OnReposicionChanged();
            }
        }
        private global::System.Int32 _Reposicion;
        partial void OnReposicionChanging(global::System.Int32 value);
        partial void OnReposicionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreUsuario
        {
            get
            {
                return _NombreUsuario;
            }
            set
            {
                OnNombreUsuarioChanging(value);
                ReportPropertyChanging("NombreUsuario");
                _NombreUsuario = StructuralObject.SetValidValue(value, false, "NombreUsuario");
                ReportPropertyChanged("NombreUsuario");
                OnNombreUsuarioChanged();
            }
        }
        private global::System.String _NombreUsuario;
        partial void OnNombreUsuarioChanging(global::System.String value);
        partial void OnNombreUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false, "Estado");
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones")]
        public CajaChica_Reposiciones CajaChica_Reposiciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CajaChica_Reposiciones> CajaChica_ReposicionesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Estados_CajaChica_Reposiciones", "CajaChica_Reposiciones", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_Reposiciones_Gastos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_Reposiciones_Gastos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_Reposiciones_Gastos object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="reposicion">Initial value of the Reposicion property.</param>
        /// <param name="rubro">Initial value of the Rubro property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="monto">Initial value of the Monto property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        /// <param name="afectaLibroCompras">Initial value of the AfectaLibroCompras property.</param>
        /// <param name="nombreUsuario">Initial value of the NombreUsuario property.</param>
        public static CajaChica_Reposiciones_Gastos CreateCajaChica_Reposiciones_Gastos(global::System.Int32 id, global::System.Int32 reposicion, global::System.Int16 rubro, global::System.String descripcion, global::System.Decimal monto, global::System.Decimal total, global::System.Boolean afectaLibroCompras, global::System.String nombreUsuario)
        {
            CajaChica_Reposiciones_Gastos cajaChica_Reposiciones_Gastos = new CajaChica_Reposiciones_Gastos();
            cajaChica_Reposiciones_Gastos.ID = id;
            cajaChica_Reposiciones_Gastos.Reposicion = reposicion;
            cajaChica_Reposiciones_Gastos.Rubro = rubro;
            cajaChica_Reposiciones_Gastos.Descripcion = descripcion;
            cajaChica_Reposiciones_Gastos.Monto = monto;
            cajaChica_Reposiciones_Gastos.Total = total;
            cajaChica_Reposiciones_Gastos.AfectaLibroCompras = afectaLibroCompras;
            cajaChica_Reposiciones_Gastos.NombreUsuario = nombreUsuario;
            return cajaChica_Reposiciones_Gastos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Reposicion
        {
            get
            {
                return _Reposicion;
            }
            set
            {
                OnReposicionChanging(value);
                ReportPropertyChanging("Reposicion");
                _Reposicion = StructuralObject.SetValidValue(value, "Reposicion");
                ReportPropertyChanged("Reposicion");
                OnReposicionChanged();
            }
        }
        private global::System.Int32 _Reposicion;
        partial void OnReposicionChanging(global::System.Int32 value);
        partial void OnReposicionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Rubro
        {
            get
            {
                return _Rubro;
            }
            set
            {
                OnRubroChanging(value);
                ReportPropertyChanging("Rubro");
                _Rubro = StructuralObject.SetValidValue(value, "Rubro");
                ReportPropertyChanged("Rubro");
                OnRubroChanged();
            }
        }
        private global::System.Int16 _Rubro;
        partial void OnRubroChanging(global::System.Int16 value);
        partial void OnRubroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontoNoImponible
        {
            get
            {
                return _MontoNoImponible;
            }
            set
            {
                OnMontoNoImponibleChanging(value);
                ReportPropertyChanging("MontoNoImponible");
                _MontoNoImponible = StructuralObject.SetValidValue(value, "MontoNoImponible");
                ReportPropertyChanged("MontoNoImponible");
                OnMontoNoImponibleChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontoNoImponible;
        partial void OnMontoNoImponibleChanging(Nullable<global::System.Decimal> value);
        partial void OnMontoNoImponibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value, "Monto");
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Decimal _Monto;
        partial void OnMontoChanging(global::System.Decimal value);
        partial void OnMontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> IvaPorc
        {
            get
            {
                return _IvaPorc;
            }
            set
            {
                OnIvaPorcChanging(value);
                ReportPropertyChanging("IvaPorc");
                _IvaPorc = StructuralObject.SetValidValue(value, "IvaPorc");
                ReportPropertyChanged("IvaPorc");
                OnIvaPorcChanged();
            }
        }
        private Nullable<global::System.Decimal> _IvaPorc;
        partial void OnIvaPorcChanging(Nullable<global::System.Decimal> value);
        partial void OnIvaPorcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Iva
        {
            get
            {
                return _Iva;
            }
            set
            {
                OnIvaChanging(value);
                ReportPropertyChanging("Iva");
                _Iva = StructuralObject.SetValidValue(value, "Iva");
                ReportPropertyChanged("Iva");
                OnIvaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Iva;
        partial void OnIvaChanging(Nullable<global::System.Decimal> value);
        partial void OnIvaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value, "Total");
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Decimal _Total;
        partial void OnTotalChanging(global::System.Decimal value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaDocumento
        {
            get
            {
                return _FechaDocumento;
            }
            set
            {
                OnFechaDocumentoChanging(value);
                ReportPropertyChanging("FechaDocumento");
                _FechaDocumento = StructuralObject.SetValidValue(value, "FechaDocumento");
                ReportPropertyChanged("FechaDocumento");
                OnFechaDocumentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaDocumento;
        partial void OnFechaDocumentoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroDocumento
        {
            get
            {
                return _NumeroDocumento;
            }
            set
            {
                OnNumeroDocumentoChanging(value);
                ReportPropertyChanging("NumeroDocumento");
                _NumeroDocumento = StructuralObject.SetValidValue(value, true, "NumeroDocumento");
                ReportPropertyChanged("NumeroDocumento");
                OnNumeroDocumentoChanged();
            }
        }
        private global::System.String _NumeroDocumento;
        partial void OnNumeroDocumentoChanging(global::System.String value);
        partial void OnNumeroDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroControl
        {
            get
            {
                return _NumeroControl;
            }
            set
            {
                OnNumeroControlChanging(value);
                ReportPropertyChanging("NumeroControl");
                _NumeroControl = StructuralObject.SetValidValue(value, true, "NumeroControl");
                ReportPropertyChanged("NumeroControl");
                OnNumeroControlChanged();
            }
        }
        private global::System.String _NumeroControl;
        partial void OnNumeroControlChanging(global::System.String value);
        partial void OnNumeroControlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Proveedor
        {
            get
            {
                return _Proveedor;
            }
            set
            {
                OnProveedorChanging(value);
                ReportPropertyChanging("Proveedor");
                _Proveedor = StructuralObject.SetValidValue(value, "Proveedor");
                ReportPropertyChanged("Proveedor");
                OnProveedorChanged();
            }
        }
        private Nullable<global::System.Int32> _Proveedor;
        partial void OnProveedorChanging(Nullable<global::System.Int32> value);
        partial void OnProveedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rif
        {
            get
            {
                return _Rif;
            }
            set
            {
                OnRifChanging(value);
                ReportPropertyChanging("Rif");
                _Rif = StructuralObject.SetValidValue(value, true, "Rif");
                ReportPropertyChanged("Rif");
                OnRifChanged();
            }
        }
        private global::System.String _Rif;
        partial void OnRifChanging(global::System.String value);
        partial void OnRifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AfectaLibroCompras
        {
            get
            {
                return _AfectaLibroCompras;
            }
            set
            {
                OnAfectaLibroComprasChanging(value);
                ReportPropertyChanging("AfectaLibroCompras");
                _AfectaLibroCompras = StructuralObject.SetValidValue(value, "AfectaLibroCompras");
                ReportPropertyChanged("AfectaLibroCompras");
                OnAfectaLibroComprasChanged();
            }
        }
        private global::System.Boolean _AfectaLibroCompras;
        partial void OnAfectaLibroComprasChanging(global::System.Boolean value);
        partial void OnAfectaLibroComprasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreUsuario
        {
            get
            {
                return _NombreUsuario;
            }
            set
            {
                OnNombreUsuarioChanging(value);
                ReportPropertyChanging("NombreUsuario");
                _NombreUsuario = StructuralObject.SetValidValue(value, false, "NombreUsuario");
                ReportPropertyChanged("NombreUsuario");
                OnNombreUsuarioChanged();
            }
        }
        private global::System.String _NombreUsuario;
        partial void OnNombreUsuarioChanging(global::System.String value);
        partial void OnNombreUsuarioChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones")]
        public CajaChica_Reposiciones CajaChica_Reposiciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CajaChica_Reposiciones> CajaChica_ReposicionesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CajaChica_Reposiciones>("ControlCajaChicaModel.FK_CajaChica_Reposiciones_Gastos_CajaChica_Reposiciones", "CajaChica_Reposiciones", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Rubros")]
        public CajaChica_Rubros CajaChica_Rubros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Rubros").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Rubros").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CajaChica_Rubros> CajaChica_RubrosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Rubros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Rubros", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_Rubros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_Rubros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_Rubros object.
        /// </summary>
        /// <param name="rubro">Initial value of the Rubro property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static CajaChica_Rubros CreateCajaChica_Rubros(global::System.Int16 rubro, global::System.String descripcion)
        {
            CajaChica_Rubros cajaChica_Rubros = new CajaChica_Rubros();
            cajaChica_Rubros.Rubro = rubro;
            cajaChica_Rubros.Descripcion = descripcion;
            return cajaChica_Rubros;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Rubro
        {
            get
            {
                return _Rubro;
            }
            set
            {
                if (_Rubro != value)
                {
                    OnRubroChanging(value);
                    ReportPropertyChanging("Rubro");
                    _Rubro = StructuralObject.SetValidValue(value, "Rubro");
                    ReportPropertyChanged("Rubro");
                    OnRubroChanged();
                }
            }
        }
        private global::System.Int16 _Rubro;
        partial void OnRubroChanging(global::System.Int16 value);
        partial void OnRubroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Reposiciones_Gastos")]
        public EntityCollection<CajaChica_Reposiciones_Gastos> CajaChica_Reposiciones_Gastos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CajaChica_Reposiciones_Gastos>("ControlCajaChicaModel.FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Reposiciones_Gastos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CajaChica_Reposiciones_Gastos>("ControlCajaChicaModel.FK_CajaChica_Reposisiones_Gastos_CajaChica_Rubros", "CajaChica_Reposiciones_Gastos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_RubrosCuentasContables")]
        public EntityCollection<CajaChica_RubrosCuentasContables> CajaChica_RubrosCuentasContables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CajaChica_RubrosCuentasContables>("ControlCajaChicaModel.FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_RubrosCuentasContables");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CajaChica_RubrosCuentasContables>("ControlCajaChicaModel.FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_RubrosCuentasContables", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_RubrosCuentasContables")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_RubrosCuentasContables : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_RubrosCuentasContables object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="rubro">Initial value of the Rubro property.</param>
        /// <param name="cuentaContableID">Initial value of the CuentaContableID property.</param>
        public static CajaChica_RubrosCuentasContables CreateCajaChica_RubrosCuentasContables(global::System.Int32 id, global::System.Int16 rubro, global::System.Int32 cuentaContableID)
        {
            CajaChica_RubrosCuentasContables cajaChica_RubrosCuentasContables = new CajaChica_RubrosCuentasContables();
            cajaChica_RubrosCuentasContables.ID = id;
            cajaChica_RubrosCuentasContables.Rubro = rubro;
            cajaChica_RubrosCuentasContables.CuentaContableID = cuentaContableID;
            return cajaChica_RubrosCuentasContables;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Rubro
        {
            get
            {
                return _Rubro;
            }
            set
            {
                OnRubroChanging(value);
                ReportPropertyChanging("Rubro");
                _Rubro = StructuralObject.SetValidValue(value, "Rubro");
                ReportPropertyChanged("Rubro");
                OnRubroChanged();
            }
        }
        private global::System.Int16 _Rubro;
        partial void OnRubroChanging(global::System.Int16 value);
        partial void OnRubroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CuentaContableID
        {
            get
            {
                return _CuentaContableID;
            }
            set
            {
                OnCuentaContableIDChanging(value);
                ReportPropertyChanging("CuentaContableID");
                _CuentaContableID = StructuralObject.SetValidValue(value, "CuentaContableID");
                ReportPropertyChanged("CuentaContableID");
                OnCuentaContableIDChanged();
            }
        }
        private global::System.Int32 _CuentaContableID;
        partial void OnCuentaContableIDChanging(global::System.Int32 value);
        partial void OnCuentaContableIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_Rubros")]
        public CajaChica_Rubros CajaChica_Rubros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_Rubros").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_Rubros").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CajaChica_Rubros> CajaChica_RubrosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_Rubros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CajaChica_Rubros>("ControlCajaChicaModel.FK_CajaChica_RubrosCuentasContables_CajaChica_Rubros", "CajaChica_Rubros", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlCajaChicaModel", Name="CajaChica_Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CajaChica_Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CajaChica_Usuarios object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cajaChica">Initial value of the CajaChica property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        /// <param name="nombreUsuario">Initial value of the NombreUsuario property.</param>
        public static CajaChica_Usuarios CreateCajaChica_Usuarios(global::System.Int32 id, global::System.Int16 cajaChica, global::System.String estado, global::System.String nombreUsuario)
        {
            CajaChica_Usuarios cajaChica_Usuarios = new CajaChica_Usuarios();
            cajaChica_Usuarios.ID = id;
            cajaChica_Usuarios.CajaChica = cajaChica;
            cajaChica_Usuarios.Estado = estado;
            cajaChica_Usuarios.NombreUsuario = nombreUsuario;
            return cajaChica_Usuarios;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CajaChica
        {
            get
            {
                return _CajaChica;
            }
            set
            {
                OnCajaChicaChanging(value);
                ReportPropertyChanging("CajaChica");
                _CajaChica = StructuralObject.SetValidValue(value, "CajaChica");
                ReportPropertyChanged("CajaChica");
                OnCajaChicaChanged();
            }
        }
        private global::System.Int16 _CajaChica;
        partial void OnCajaChicaChanging(global::System.Int16 value);
        partial void OnCajaChicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false, "Estado");
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreUsuario
        {
            get
            {
                return _NombreUsuario;
            }
            set
            {
                OnNombreUsuarioChanging(value);
                ReportPropertyChanging("NombreUsuario");
                _NombreUsuario = StructuralObject.SetValidValue(value, false, "NombreUsuario");
                ReportPropertyChanged("NombreUsuario");
                OnNombreUsuarioChanged();
            }
        }
        private global::System.String _NombreUsuario;
        partial void OnNombreUsuarioChanging(global::System.String value);
        partial void OnNombreUsuarioChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlCajaChicaModel", "FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_CajasChicas")]
        public CajaChica_CajasChicas CajaChica_CajasChicas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_CajasChicas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_CajasChicas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CajaChica_CajasChicas> CajaChica_CajasChicasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_CajasChicas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CajaChica_CajasChicas>("ControlCajaChicaModel.FK_CajaChica_Usuarios_CajaChica_CajasChicas", "CajaChica_CajasChicas", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
