/*    
	  Jueves, 12 de Septiembre de 2.024  -   v0.00.461.sql 
	  
	  Agregamos un pk a la tabla tVersionWeb
*/


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tVersionWeb ADD CONSTRAINT
	PK_tVersionWeb PRIMARY KEY CLUSTERED 
	(
	VersionActual
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.tVersionWeb SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


Delete From tVersionWeb
Insert Into tVersionWeb(VersionActual, Fecha) Values('v0.00.461', GetDate()) 